# Generated by Django 3.2.9 on 2021-11-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_consulta_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especializacao',
            field=models.CharField(choices=[('C', 'Cardiologista'), ('P', 'Pediatra'), ('U', 'Urologista'), ('G', 'Geriatria'), ('O', 'Oftalmologia'), ('D', 'Dermatologia'), ('E', 'Emergência'), ('I', 'Infectologia')], max_length=1),
        ),
    ]
