# Generated by Django 3.2.9 on 2021-11-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211124_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='senha',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
