# Generated by Django 3.2.9 on 2021-11-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_especializacao_especializacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especializacao',
            name='especializacao',
            field=models.CharField(choices=[('C', 'Cardiologista'), ('P', 'Pediatra'), ('U', 'Urologista'), ('G', 'Geriatria'), ('O', 'Oftalmologia'), ('D', 'Dermatologia'), ('E', 'Emergência'), ('I', 'Infectologia')], max_length=1),
        ),
    ]
