# Generated by Django 3.2.9 on 2021-11-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_especializacao_especializacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especializacao',
            name='especializacao',
            field=models.CharField(max_length=40),
        ),
    ]
