# Generated by Django 3.2.9 on 2021-11-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_medico_especializacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especializacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.especializacao'),
        ),
    ]
